# Generated by Django 3.0 on 2025-10-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockedapps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=20)),
                ('totelsem', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departementname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labname', models.CharField(max_length=20)),
                ('labno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laballocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('LAB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Labassistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labassistantname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Labsubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemno', models.CharField(max_length=20)),
                ('macaddress', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Systemallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('LABALLOCATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Laballocation')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.System')),
            ],
        ),
        migrations.CreateModel(
            name='Newapps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('appname', models.CharField(max_length=50)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.System')),
            ],
        ),
        migrations.CreateModel(
            name='Labsubjectschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('fromtime', models.CharField(max_length=20)),
                ('totime', models.CharField(max_length=20)),
                ('LABALLOCATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Laballocation')),
                ('LABSUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Labsubject')),
            ],
        ),
        migrations.AddField(
            model_name='laballocation',
            name='LABASSIST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Staff'),
        ),
        migrations.CreateModel(
            name='Keylogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.System')),
            ],
        ),
        migrations.CreateModel(
            name='Helprequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Staff')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Healthreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvedstatus', models.CharField(max_length=50)),
                ('problem', models.CharField(max_length=50)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.System')),
            ],
        ),
        migrations.CreateModel(
            name='Filelogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.System')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='DEP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Departement'),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.System')),
            ],
        ),
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
    ]
